# This is a config for E2B sandbox template.
# You can use template ID (556b6kxjskfc43ihwsg7) or template name (nextjs-code-agent-template2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("nextjs-code-agent-template2") # Sync sandbox
# sandbox = await AsyncSandbox.create("nextjs-code-agent-template2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('nextjs-code-agent-template2')

team_id = "ba7b10f6-cb1e-40d4-8598-87f88fd33169"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "nextjs-code-agent-template2"
template_id = "556b6kxjskfc43ihwsg7"
